# Databricks Apps 배포 설정
# 앱 이름: jw-rag-chat

# 시작 명령
command:
  - "python"
  - "app.py"

# 리소스 권한
resources:
  - name: rag-agent
    serving_endpoint:
      name: agents_jaewoo_catalog-mlfow_eval-rag_agent_v2
      permission: CAN_QUERY

# 환경 변수
env:
  # Agent 설정 - 올바른 엔드포인트로 수정됨
  - name: AGENT_ENDPOINT_URL
    value: "https://e2-demo-field-eng.cloud.databricks.com/serving-endpoints/agents_jaewoo_catalog-mlfow_eval-rag_agent_v2/invocations"
  
  # Databricks 인증
  # Databricks Apps는 자동으로 Service Principal 토큰을 제공합니다
  # DATABRICKS_TOKEN 환경 변수는 자동으로 주입됩니다
  
  # Unity Catalog 설정
  - name: CATALOG_NAME
    value: "jaewoo_catalog"
  
  - name: SCHEMA_NAME
    value: "mlfow_eval"
  
  - name: VOLUME_NAME
    value: "volume01"
  
  - name: VOLUME_BASE_PATH
    value: "/Volumes/jaewoo_catalog/mlfow_eval/volume01"
  
  - name: VECTOR_SEARCH_INDEX
    value: "jaewoo_catalog.mlfow_eval.chunked_documents_index"
  
  # 세션 설정
  - name: SESSION_TIMEOUT_MINUTES
    value: "60"
  
  - name: MAX_HISTORY_TURNS
    value: "5"
  
  # 파일 업로드 설정
  - name: ALLOWED_FILE_TYPES
    value: "pdf,docx,pptx,txt,xlsx"
  
  - name: MAX_UPLOAD_MB
    value: "10"
  
  # Flask 설정
  - name: FLASK_DEBUG
    value: "False"
  
  - name: LOG_LEVEL
    value: "INFO"
  
  - name: PORT
    value: "8000"
